name: Create Archive
on: 
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set env version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: '${{ github.event.repository.owner }}.${{ github.event.repository.name }}.${{ steps.get_version.outputs.VERSION }}.sbslib'
        #directory: 'sbs_utils'
        #exclusions: 'LICENSE. *.* .* *. *.git* /docs/* /mock/* /typings/* /sphinx/* /tests/* *.py .nojekyll'
        path: "sbs_utils"

    - name: Archive Typings Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: '${{ github.event.repository.name }}.${{ steps.get_version.outputs.VERSION }}.types.zip'
        # directory: 'typings'
        #exclusions: 'LICENSE. *.* *.git* .* *. /docs/* /mock/* /sbs_utils/* /sphinx/* /tests/*'
        path: "typings"

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ github.event.repository.owner }}.${{ github.event.repository.name }}.${{ steps.get_version.outputs.VERSION }}.sbslib,${{ github.event.repository.name }}.${{ steps.get_version.outputs.VERSION }}.types.zip"
        token: ${{ secrets.GITHUB_TOKEN }}

